# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run File
      run: mvn clean test --file pom.xml
    - name: Inatll allure command line
      if: ${{ always() }}
      run: npm install -g allure-commandline --save-dev
    - name: Create Allure Report
      if: ${{ always() }}
      run: allure generate -c ./allure-results -o ./allure-reports
    - name: Upload Allure Test Result
      if: ${{ always() }}
      uses: actions/upload-artifact@v2.1.4
      with:
        name: Test Result-Allure
        path: ./allure-reports
    - name: Upload Extened Test Result
      if: ${{ always() }}
      uses: actions/upload-artifact@v2.1.4
      with:
        name: Test Result-Extended
        path: ./ExtentReports/*.html


